# Generated by Django 3.1 on 2020-08-12 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('liked', models.TextField(blank=True, null=True)),
                ('disliked', models.TextField(blank=True, null=True)),
                ('other_comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
