# Generated by Django 3.1 on 2020-08-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='action_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
