apiVersion: v1
kind: ConfigMap
metadata:
  name: feedback-nginx-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  4;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  4096;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;
      sendfile        on;
      tcp_nopush   on;
      keepalive_timeout  65;
      gzip  on;
      gzip_proxied no_etag;
      client_max_body_size 0;

      server {
        listen       [::]:80;
        server_name  feedback.glauca.digital;

        root /data/;

        location / {
          try_files $uri @proxy_to_app;
        }

        location @proxy_to_app {
          proxy_pass      http://feedback-django:8000;

          proxy_http_version 1.1;

          proxy_redirect off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Host $server_name;
          proxy_set_header X-Forwarded-Proto https;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-nginx
  labels:
    app: feedback
    part: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback
      part: nginx
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: feedback
        part: nginx
    spec:
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: feedback-django-static
        - name: conf
          configMap:
            name: feedback-nginx-conf
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/data/static/"
              name: static
            - mountPath: "/etc/nginx/nginx.conf"
              name: conf
              subPath: "nginx.conf"
---
apiVersion: v1
kind: Service
metadata:
  name: feedback-nginx
  labels:
    app: feedback
    part: nginx
spec:
  selector:
    app: feedback
    part: nginx
  ports:
    - port: 80
      targetPort: 80
      name: nginx
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: feedback-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
    - hosts:
        - feedback.glauca.digital
      secretName: feedback-tls
  rules:
  - host: feedback.glauca.digital
    http:
      paths:
      - path: /
        backend:
          serviceName: feedback-nginx
          servicePort: 80
